Add 2.22.0 release
percona/community pull request #125
Opened 2021-09-16 19:47 UTC by denisok

Add community preview for 2.22.0

2021-09-16 19:48 UTC, denisok commented
@rnovikovP please check

2021-09-16 20:12 UTC, shoffman-percona requested changes
some cleanup suggestions

2021-09-16 20:12 UTC, shoffman-percona commented on content/blog/2021-09-16-2-22-0-preview.md
> +Please also check out our Engineering Monthly Meetings https://percona.community/contribute/engineeringmeetings/ and join us on our journey in OpenSource! Contact us in [per.co.na/discord](https://pe
Need to hint to people what to do when done testing?  
disable testing repo...roll back client version
maybe recommend test in a sandbox/vm vs on your live system?

2021-09-16 20:12 UTC, shoffman-percona commented on content/projects/pmm.md
> +Please check what is in PMM Roadmap on this [Dashboard](https://jira.percona.com/secure/Dashboard.jspa?selectPageId=13502), choose "PMM" in Roadmap picker.
```suggestion
Please check out the PMM Roadmap on this [Dashboard](https://jira.percona.com/secure/Dashboard.jspa?selectPageId=13502), choose the project "Percona Monitoring and Management (PMM)" in All Product Issues/Roadmap picker.
```

2021-09-16 20:12 UTC, shoffman-percona commented on content/blog/2021-09-16-2-22-0-preview.md
> +https://jira.percona.com/browse/PMM-8829
```suggestion
- [PMM-8829](https://jira.percona.com/browse/PMM-8829) - "Missing Listen Port" error for external exporters after restart
```

2021-09-16 20:12 UTC, shoffman-percona commented on content/blog/2021-09-16-2-22-0-preview.md
> +https://deploy-preview-588--pmm-doc.netlify.app/release-notes/2.22.0.html
```suggestion
Release Notes Preview found [here](https://deploy-preview-588--pmm-doc.netlify.app/release-notes/2.22.0.html)
```

2021-09-16 20:12 UTC, shoffman-percona commented on content/blog/2021-09-16-2-22-0-preview.md
> +https://www.percona.com/doc/percona-monitoring-and-management/2.x/setting-up/server/virtual-appliance.html
```suggestion
[Instructions](https://www.percona.com/doc/percona-monitoring-and-management/2.x/setting-up/server/virtual-appliance.html)
```

2021-09-16 20:12 UTC, shoffman-percona commented on content/blog/2021-09-16-2-22-0-preview.md
> +https://www.percona.com/doc/percona-monitoring-and-management/2.x/setting-up/server/docker.html
```suggestion
[Instructions](https://www.percona.com/doc/percona-monitoring-and-management/2.x/setting-up/server/docker.html)
```

2021-09-16 21:14 UTC, denisok commented on content/blog/2021-09-16-2-22-0-preview.md
> +Please also check out our Engineering Monthly Meetings https://percona.community/contribute/engineeringmeetings/ and join us on our journey in OpenSource! Contact us in [per.co.na/discord](https://pe
added a hint

2021-09-16 21:43 UTC, shoffman-percona approved these changes

2021-09-17 05:53 UTC, PaulJacobs-percona commented on content/blog/2021-09-16-2-22-0-preview.md
> +Percona Monitoring and Management 2.22.0 is released today as a Community preview.
What does 'Community preview' mean? How is it different to a normal release?

2021-09-17 05:56 UTC, PaulJacobs-percona submitted a review, later dismissed

2021-09-17 05:56 UTC, PaulJacobs-percona commented on content/blog/2021-09-16-2-22-0-preview.md
> +Please try it out only in **testing environment**, those packages and images aren't supposed to be deployed in production systems. Final version is expected to be released through the standard channe
```suggestion
We encourage you to try this PMM community release in **testing environments** only, as these packages and images are not fully production-ready. The final version is expected to be released through the standard channels in the coming week.
```

2021-09-17 08:36 UTC, denisok commented on content/blog/2021-09-16-2-22-0-preview.md
> +Percona Monitoring and Management 2.22.0 is released today as a Community preview.
no idea, this is first try. we will come up with something better.
it is like Early Preview probably.

2021-09-17 09:31 UTC, denisok commented on content/blog/2021-09-16-2-22-0-preview.md
> +Percona Monitoring and Management 2.22.0 is released today as a Community preview.
what is the better name ?

2021-09-17 10:17 UTC, rnovikovP commented on content/blog/2021-09-16-2-22-0-preview.md
> +Percona Monitoring and Management 2.22.0 is released today as a Community preview.
```suggestion
Percona Monitoring and Management 2.22.0 is released today as a Preview Release.
```

2021-09-17 10:17 UTC, rnovikovP commented on content/blog/2021-09-16-2-22-0-preview.md
> +We encourage you to try this PMM community release in **testing environments** only, as these packages and images are not fully production-ready. The final version is expected to be released through
```suggestion
We encourage you to try this PMM Preview Release in **testing environments** only, as these packages and images are not fully production-ready. The final version is expected to be released through the standard channels in the coming week.
```

2021-09-17 11:38 UTC, denisok commented
@dbazhenov could you please advertise this after it lands ?

2021-09-17 12:00 UTC, rnovikovP approved these changes
LGTM

2021-09-17 12:34 UTC, merged